# Generated by Django 3.2.7 on 2021-10-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('broad_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Goods.broadcategories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Goods.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_discount', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(blank=True)),
                ('description_discount_price', models.TextField(blank=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('size', models.CharField(default='Потом допилю(розмір)', max_length=50)),
                ('brand', models.CharField(default='Потом допилю(бренд)', max_length=50)),
                ('color', models.CharField(default='Потом допилю(цвет)', max_length=50)),
                ('material', models.CharField(default='Потом допилю(Материал)', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Goods.subcategories')),
            ],
        ),
    ]
