# Generated by Django 3.2.7 on 2021-10-05 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_auto_20211005_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
