# Generated by Django 3.2.7 on 2021-10-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_featuresads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresads',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
