# Generated by Django 3.2.7 on 2021-10-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_auto_20211005_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='category',
            new_name='sub_category',
        ),
    ]
